networks:
  mango-network:
    driver: bridge

volumes:
  postgres-mango-data:
  redis-data:
  consul-data:
  kafka-data:

services:
  # Mango database service
  postgres-mango:
    image: postgres:latest
    # For apple silicon host. For other hosts, use linux/amd64
    platform: linux/arm64
    container_name: mango-database
    environment:
      POSTGRES_DB: mangodb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-mango-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mango-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {POSTGRES_USER} -d mangodb"]
      interval: 10s
      timeout: 5s
      retries: 5