networks:
  mango-network:
    driver: bridge

volumes:
  postgres-mango-data:
  redis-data:
  consul-data:
  kafka-data:

services:
  # Mango database service
  postgres-mango:
    image: postgres:latest
    # For apple silicon host. For other hosts, use linux/amd64
    platform: linux/arm64
    container_name: mango-database
    environment:
      POSTGRES_DB: mangodb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-mango-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mango-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {POSTGRES_USER} -d mangodb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mango database connection pooling service
  pgbouncer-mango:
    image: edoburu/pgbouncer:latest
    container_name: mango-pgbouncer
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-mango:5432/mangodb
      # Match password type with postgres database
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
      MIN_POOL_SIZE: 5
      RESERVE_POOL_SIZE: 5
      RESERVE_POOL_TIMEOUT: 3
      MAX_DB_CONNECTIONS: 50
      MAX_USER_CONNECTIONS: 50
    ports:
      - "6432:5432"
    depends_on:
      postgres-mango:
        condition: service_healthy
    networks:
      - mango-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5